# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.cache/wt [current_project]
set_property parent.project_path D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Vivado2018_wrk/UART_ILA_pack/ip_repo [current_project]
set_property ip_output_repo d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_data.coe
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_address.coe
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_1_data.coe
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_1_address.coe
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_2_data.coe
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_2_address.coe
read_verilog -library xil_defaultlib D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/hdl/axi_spi_top_wrapper.v
add_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/axi_spi_top.bd
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/axi_spi_top_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/axi_spi_top_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/axi_spi_top_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/ip_0/axi_spi_top_jesd204_0_0_phy_gt.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/ip_0/axi_spi_top_jesd204_0_0_phy_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/synth/axi_spi_top_jesd204_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/synth/axi_spi_top_jesd204_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_xbar_0/axi_spi_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_0/axi_spi_top_axi_traffic_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_1/axi_spi_top_axi_traffic_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_2/axi_spi_top_axi_traffic_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_vio_0_0/axi_spi_top_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_vio_0_0/axi_spi_top_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_auto_pc_0/axi_spi_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/axi_spi_top_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc
set_property used_in_implementation false [get_files D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top axi_spi_top_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_spi_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_spi_top_wrapper_utilization_synth.rpt -pb axi_spi_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
